-- apaga todos os dados de todas as tabelas

DELETE FROM INSTITUTO;
DELETE FROM CURSO;
DELETE FROM DISCIPLINA;
DELETE FROM PROFESSOR;
DELETE FROM SALA;
DELETE FROM HORARIO;
DELETE FROM TURMA;
DELETE FROM MATRICULA;
DELETE FROM CURSO_INSTITUTO;
DELETE FROM DISCIPLINA_CURSO;
DELETE FROM REQUISITO;
DELETE FROM ALUNO;
DELETE FROM FUNCIONARIO_ADM;
DELETE FROM DEPARTAMENTO;
DELETE FROM PREDIO;
