CREATE VIEW Alunos_Ativos AS
SELECT CPF, RG, NOME, DATA_NASC, RUA, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, ESTADO, PAIS, TELEFONE, EMAIL, MATRICULA, ETAPA, SEMESTRE_INGRESSO, CREDITOS_OBTIDOS, ATIVO, SIGLA_CURSO
FROM ALUNO
WHERE ATIVO = 1;