IF EXISTS (select * from sys.databases where name = 'UNIVERSIDADE')
BEGIN
	USE master
    DROP DATABASE UNIVERSIDADE
END
    CREATE DATABASE UNIVERSIDADE;
GO

USE UNIVERSIDADE

CREATE TABLE INSTITUTO (
	COD_INST INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(120) NOT NULL,
	SIGLA VARCHAR(10) NOT NULL);

CREATE TABLE DEPARTAMENTO (
	COD_DEPTO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(120) NOT NULL,
	SIGLA VARCHAR(10) NOT NULL,
	COD_INST INT NOT NULL,
	foreign key (COD_INST) references INSTITUTO);

CREATE TABLE ALUNO (
	CPF VARCHAR(14) PRIMARY KEY,
	RG BIGINT UNIQUE NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	DATA_NASC DATE NOT NULL,
	RUA VARCHAR(50) NOT NULL,
	NUMERO INT NOT NULL,
	COMPLEMENTO VARCHAR(50),
	BAIRRO VARCHAR(40) NOT NULL,
	CEP INT NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL,
	PAIS VARCHAR(30) NOT NULL,
	TELEFONE VARCHAR(14) NOT NULL,
	EMAIL VARCHAR(120) NOT NULL,
	MATRICULA VARCHAR(6) UNIQUE NOT NULL,
	ETAPA TINYINT NOT NULL,
	SEMESTRE_INGRESSO VARCHAR(6) NOT NULL,
	CREDITOS_OBTIDOS INT DEFAULT 0 NOT NULL,
	ATIVO TINYINT DEFAULT 1 NOT NULL
);

CREATE TABLE PROFESSOR (
	CPF VARCHAR(14) PRIMARY KEY,
	RG BIGINT UNIQUE NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	DATA_NASC DATE NOT NULL,
	RUA VARCHAR(50) NOT NULL,
	NUMERO INT NOT NULL,
	COMPLEMENTO VARCHAR(50),
	BAIRRO VARCHAR(40) NOT NULL,
	CEP INT NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL,
	PAIS VARCHAR(30) NOT NULL,
	TELEFONE VARCHAR(14) NOT NULL,
	EMAIL VARCHAR(120) NOT NULL,
	MATRICULA VARCHAR(6) UNIQUE NOT NULL,
	ESPECIALIZACAO VARCHAR(200) NOT NULL,
	COD_DEPTO INT NOT NULL,
	foreign key (COD_DEPTO) references DEPARTAMENTO);

CREATE TABLE FUNCIONARIO_ADM (
	CPF VARCHAR(14) PRIMARY KEY,
	RG BIGINT UNIQUE NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	DATA_NASC DATE NOT NULL,
	RUA VARCHAR(50) NOT NULL,
	NUMERO INT NOT NULL,
	COMPLEMENTO VARCHAR(50),
	BAIRRO VARCHAR(40) NOT NULL,
	CEP INT NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL,
	PAIS VARCHAR(30) NOT NULL,
	TELEFONE VARCHAR(14) NOT NULL,
	EMAIL VARCHAR(120) NOT NULL,
	CARGO VARCHAR(30) NOT NULL,
	COD_INST INT,
	COD_DEPTO INT,
	foreign key (COD_INST) references INSTITUTO,
	foreign key (COD_DEPTO) references DEPARTAMENTO);
	

INSERT INTO INSTITUTO values ('A', 'a'), ('B', 'b');
SELECT * FROM INSTITUTO