CREATE VIEW Alunos_Ativos AS
SELECT CPF, RG, NOME, DATA_NASC, RUA, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, ESTADO, PAIS, TELEFONE, EMAIL, MATRICULA, ETAPA, SEMESTRE_INGRESSO, CREDITOS_OBTIDOS, ATIVO, SIGLA_CURSO
FROM ALUNO
WHERE ATIVO = 1;

SELECT SIGLA_CURSO, COUNT(*) AS NUM_ALUNOS
FROM Alunos_Ativos
GROUP BY SIGLA_CURSO
HAVING COUNT(*) > 1;

SELECT SIGLA_CURSO, COUNT(*) AS NUM_ALUNOS_PRIMEIRO_SEMESTRE
FROM Alunos_Ativos
WHERE CREDITOS_OBTIDOS = 0
GROUP BY SIGLA_CURSO;